services:
  frontend:
    build:
      context: ./frontend
    container_name: front
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    command: npm run dev
    networks:
      - mern-network

  backend:
    build:
      context: .
    container_name: back
    ports:
      - "5000:5000"
    networks:
      - mern-network
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    networks:
      - mern-network

networks:
  mern-network:

volumes:
  mongo-data:
